name: AI Whip
favicon: null
layout_spectrum: 0.8272295363713056
typography_spectrum: 0.12796852132305503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.35009428462944925
  lightness: 0.020836545852944255
  saturation: 0.6296193420421332
  rhythmicContrast: 0.840758976759389
purpose: []
